### ISSUE TITLE
Model Data for WSI Compatible CSV export

### ISSUE THREAD

**Issue by chriscocker** [CST299TeamD/BearWatch#24]
Review WSI export sheet and determine how application will store and ready the data for export

**Comment by peterplatten** [comment]
Have received an Excel sheet template from MoE.

**Comment by peterplatten** [comment]
Modified the old ERD to be able to handle everything currently in the prototype, and everything that I believe is likely to be added from the WSI templates. Also reformatted it so that we should be able to populate the CSV with less difficulty, and to provide the running application with variables to populate pages with.

Reviewed with Chris.
